# AntiBot by LinsaFTW
# Please help by donating, we require funds to continue with the development.
# https://paypal.me/LinsaFTW
#

# Condition System - (Protection Mode)
#
# PPS -> Pings/second (IPs that pinged the server in the last second)
# CPS -> Connections/second (IPs that are connecting but got cancelled in the last second)
# JPS -> Joins/second (IPs that passed the checks and joined in the last second)
#
# This example means "The server needs any PPS, 4 CPS and 1 JPS to activate the module".
# conditions:
#   PPS: 0
#   CPS: 4
#   JPS: 1
#
# When the conditions are achieved the module will start blocking bots.
# If not, the module wont check anyone. (Made to only work while attack)
# Setting all conditions to 0 will keep the module always active.
#

# Default plugin language. (This will change depending on the player's language)
lang: "en"

# Notifies console and players with permissions about punishments made.
notifications:
  enabled: true

  # Allows logging notifications on the console.
  console: true

# Module that handles player data stored to detect bots.
player:
  # Time to wait before removing disconnected players from the cache. (In milliseconds)
  cache_time: 15000

# Adds real players to a list on disconnect so they can bypass the checks.
# If conditions are achieved Lockout will activate and only Whitelisted will be able to join.
# Lockout is made for security measures and its not intended to be used normally.
whitelist:
  enabled: true

  conditions:
    pps: 40
    cps: 0
    jps: 20

  time:
    # Time in milliseconds the player has to be online to get whitelisted.
    whitelist: 5000

    # Time in milliseconds the lockout runs active after conditions are met.
    lockout: 20000

  commands:
    - "disconnect %kick_whitelist%"

# This check blocks Blacklisted IPs if conditions are achieved.
blacklist:
  enabled: true

  conditions:
    pps: 0
    cps: 3
    jps: 0

  commands:
    - "disconnect %kick_blacklist%"

# Checks if connections have abnormal behaviour to prevent attacks from single IPs.
ratelimit:
  enabled: true

  # Conditions to block a connection. (Connection needs to reach one of this values to get blocked)
  # This basically limits how much of this actions a single IP can do per second.
  conditions:
    pps: 8
    cps: 3
    jps: 2

  # Minimum time forced between connections from the same IP. (In milliseconds)
  throttle: 650

  # Max players that can be online at the same time from the same IP.
  max_online: 3

  commands:
    - "disconnect %kick_ratelimit%"

# Checks if connections have bot nicknames.
nickname:
  enabled: true

  conditions:
    pps: 0
    cps: 4
    jps: 0

  # Checks if the nickname contains any of this strings.
  blacklist:
    - "mcspam"
    - "mcstorm"
    - "mcdrop"

  commands:
    - "disconnect %kick_nickname%"

# Forces connections to reconnect if they arent whitelisted.
reconnect:
  enabled: true

  # Asks to ping before reconnecting to increase protection.
  ping: true

  # Times connections have to reconnect the server.
  times: 3

  conditions:
    pps: 0
    cps: 3
    jps: 1

  # Time to wait to reconnect for the first time. (In milliseconds)
  throttle: 800

  commands:
    - "disconnect %kick_reconnect%"

# Blocks connections that didnt send the Settings packet.
# WARNING: Disable if you have false positives with Multi-Lobby and Minechat. (Not recommended)
settings:
  enabled: true

  # Delay after joining to check if player sent Settings packet. (In milliseconds)
  delay: 5000

  conditions:
    pps: 0
    cps: 0
    jps: 0

  commands:
    - "disconnect %kick_settings%"

# Blocks connections that chat too fast or in invalid moments.
fastchat:
  enabled: true

  conditions:
    pps: 0
    cps: 3
    jps: 2

  # Time until the check stops monitoring the player. (In milliseconds)
  time: 750

  commands:
    - "disconnect %kick_fastchat%"

# Checks if different connections try to register with the same password.
register:
  enabled: true

  conditions:
    pps: 0
    cps: 0
    jps: 0

  commands:
    - "disconnect %kick_register%"

# Checks if there are too many different nicknames from the same IP.
accounts:
  enabled: true

  # Max different nicknames a player can login while the check is active.
  limit: 2

  conditions:
    pps: 0
    cps: 6
    jps: 1

  commands:
    - "disconnect %kick_accounts%"
